spring.application.name=itic
server.servlet.context-path=/api
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
server.forward-headers-strategy=framework

# OAuth2 Google Configuration
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=${app.backend.url}/api/login/oauth2/code/google

# AWS Cognito Configuration
aws.cognito.region=${AWS_COGNITO_REGION:us-east-1}

# JWT Configuration
app.jwt.secret=${JWT_SECRET:vY29tZS10by1teS1hdzNzb21lLWFnZW5kYS1hcGktcHJvamVjdC13aXRoLWp3dC10b2tlbnM=}

# Data Source
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
springdoc.swagger-ui.display-request-duration=true
# springdoc.server-url=https://api.manzanaazul.cat/api
